esphome:
  name: froggy-battery
  friendly_name: Froggy Battery

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80: y

logger:
  baud_rate: 0

external_components:
  - source:
      type: git
      url: https://github.com/dz0ny/esphome-bthome
      ref: pull/19/head
    components: [bthome]

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT22
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: hum
      name: "Humidity"
    update_interval: 60s

bthome:
  ble_stack: nimble
  min_interval: 2s
  max_interval: 4s
  tx_power: 0
  retransmit_count: 2
  retransmit_interval: 400ms
  sensors:
    - type: temperature
      id: temp
    - type: humidity
      id: hum

deep_sleep:
  run_duration: 10s
  sleep_duration: 290s